config/routes.rb
Rails.application.routes.draw do 
  devise_for :users

   
  get 'home/show' 
  post 'home/show', to: 'home#reroute'  
  
  get 'home/video_form'
  get 'home/video_success'
  post 'home/video_success'
 
  get 'show/:emotion/:media', to: 'home#show', as: 'emotion_media' 
  get 'home/contact' 
  

  root 'home#index'

end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :emotions, through: :color_emotions
	has_many :color_emotions
end

app/models/color_emotion.rb
class ColorEmotion < ActiveRecord::Base
	belongs_to :color
	belongs_to :emotion
end

app/models/emotion.rb
class Emotion < ActiveRecord::Base
	has_many :colors, through: :color_emotions
	has_many :color_emotions
	has_many :videos, through: :video_emotions
	has_many :video_emotions
	has_many :musics, through: :music_emotions
	has_many :music_emotions
	has_many :images, through: :image_emotions
	has_many :image_emotions
end

app/models/image.rb
class Image < ActiveRecord::Base
	has_many :emotions, through: :image_emotions
	has_many :image_emotions
	belongs_to :emotions
end

app/models/image_emotion.rb
class ImageEmotion < ActiveRecord::Base
	belongs_to :image 
	belongs_to :emotion 
end

app/models/music.rb
class Music < ActiveRecord::Base
	has_many :emotions, through: :music_emotions
	has_many :music_emotions
end

app/models/music_emotion.rb
class MusicEmotion < ActiveRecord::Base
	belongs_to :music 
	belongs_to :emotion
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable#, :validatable

  #validations
  validates :username, uniqueness: true, length: {minimum: 3, maximum: 16}

  #relationships
  has_many :images
  has_many :videos
  has_many :musics 
end

app/models/video.rb
class Video < ActiveRecord::Base
	has_many :emotions, through: :video_emotions
	has_many :video_emotions
end

app/models/video_emotion.rb
class VideoEmotion < ActiveRecord::Base
	belongs_to :video 
	belongs_to :emotion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters 
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :fname, :lname, :email, :password) }
	end
 	



	#helper methods
 	def emotion_id(emotion)
		Emotion.where(name: emotion).first.id
	end

	def find_images(emotion)
		img_ids = []
  	imgs = []

		ImageEmotion.where(emotion_id: emotion_id(emotion)).each do |ie|
      img_ids << ie.image_id
    end

    img_ids.each do |id|
      img = Image.find(id)
    	imgs << img
    end

    return imgs
	end

	def images_name(music_collection)
		array = []
		music_collection.each do |image|
  		array << image.name
		end

		return array.join(',') 
	end 

	def find_videos(emotion)
		vid_ids = []
  	vids = []

		VideoEmotion.where(emotion_id: emotion_id(emotion)).each do |ve|
      vid_ids << ve.video_id
    end

    vid_ids.each do |id|
      vid = Video.find(id)
    	vids << vid
    end

    return vids
	end

	
	def find_music(emotion)
		music_ids = []
		musics = []

		MusicEmotion.where(emotion_id: emotion_id(emotion)).each do |me|
			music_ids << me.music_id
		end

		music_ids.each do |id|
			music = Music.find(id)
			musics << music
		end

		return musics
	end 

	def music_file(music_collection)
		array = []
		music_collection.each do |music|
  		array << music.file.split('/')[-1]
		end

		return array.join(',') 
	end 

	def music_name(music_collection)
		array = []
		music_collection.each do |music|
  		array << music.name
		end

		return array.join(',') 
	end 
	
	def find_colors(emotion)
		colors_ids = []
  	cols = []

		ColorEmotion.where(emotion_id: emotion_id(emotion)).each do |ce|
      colors_ids << ce.color_id
    end

    colors_ids.each do |id|
      col = Color.find(id)
    	cols << col
    end

    return cols
	end

	def get_color(emotion)
		findColors = find_colors(emotion)
		findColors[rand(0..findColors.size-1)]
	end

	def hexcodes(colors)
		# #returns a list of hexcodes as a string
		array = []

		colors.each do |color|
			array << color.hexcode
		end 
		return array.join(',') 
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
	def video_form
    @video = Video.new
  end

  def video_success
		@name = params[:name]
		@file = params[:file]
		puts '&' *50
		puts @name
		puts @file
		puts '&' *50
			Video.save name:(@name), file:(@file)
      flash[:notice]="Video Saved for Review"
	end

  def index
  	@emotions = Emotion.all 
  end

  def reroute
    emotion = Emotion.find(params[:emotion]) 
    redirect_to emotion_media_path(emotion.name, params[:media]) 
  end 

  def show  
  	@emotion = Emotion.find_by_name(params[:emotion])  
    @selected = params[:media]   
    @colors = find_colors(@emotion.name) 
    @hexcodes = hexcodes(@colors)
    @music_collection = find_music(@emotion.name)
    @music_file = music_file(@music_collection)
    @music_name = music_name(@music_collection)
    @images = find_images(@emotion.name) 
    @images_name = images_name(@images)  
     
    if @selected == 'video'
      @alternate = 'music'
    elsif @selected == 'music'
      @alternate = 'video'
    else
    end
  end 
 
 
end

app/helpers/application_helper.rb
module ApplicationHelper 
	def resource_name
    :user
  end

	def resource
	   @resource ||= User.new
	end

	def devise_mapping
	  @devise_mapping ||= Devise.mappings[:user]
	end 

	def emotion_id(emotion)
		Emotion.where(name: emotion).first.id
	end

	def find_images(emotion)
		img_ids = []
  	imgs = []

		ImageEmotion.where(emotion_id: emotion_id(emotion)).each do |ie|
      img_ids << ie.image_id
    end

    img_ids.each do |id|
      img = Image.find(id)
    	imgs << img
    end

    return imgs
	end

	def find_videos(emotion)
		vid_ids = []
  	vids = []

		VideoEmotion.where(emotion_id: emotion_id(emotion)).each do |ve|
      vid_ids << ve.video_id
    end

    vid_ids.each do |id|
      vid = Video.find(id)
    	vids << vid
    end

    return vids
	end

	
	def find_music(emotion)
		music_ids = []
		musics = []

		MusicEmotion.where(emotion_id: emotion_id(emotion)).each do |me|
			music_ids << me.music_id
		end

		music_ids.each do |id|
			music = Music.find(id)
			musics << music
		end

		return musics
	end

	def return_url
		find_music(@emotion.name).each do |music|
  		music = music.file
		end

		return music
	end 
	
	def find_colors(emotion)
		colors_ids = []
  	cols = []

		ColorEmotion.where(emotion_id: emotion_id(emotion)).each do |ce|
      colors_ids << ce.color_id
    end

    # colors_ids.each do |id|
    #   col = Color.find(id)
    # 	cols << col
    # end

    return cols
	end

	def get_color(emotion)
		findColors = find_colors(emotion)
		findColors[rand(0..findColors.size-1)]
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<div class="contact-form">
	<h1 id="contact">Contact Us</h1> 
	<%= form_tag do %>  
		<%= email_field_tag :email, placeholder = 'Email Address', class: :contact_email %>
    <br/><br/>
    <%= text_area_tag :comment, placeholder = 'Enter comment here...', class: :contact_comment %> 
    <br/><br/>
		<%= submit_tag 'Send', class: :submit_button %>
	<% end %>
</div> 

app/views/home/index.html.erb
<div id="wrapper">
<div class="home_index">

	<!-- if user_signed_in?  have to check where the menu is and hide sign in and sign up -->

	<h1 id="feel">I want to feel... </h1>
	 
	<div class="form"> 
		<%= form_tag(home_show_path, method: :post) do %>  
			<%= select_tag(:emotion, options_for_select(
				[['happy', emotion_id("happy")],
				 ['sad',   emotion_id("sad")  ],
				 ['angry', emotion_id("angry")],
				 ['calm',  emotion_id("calm") ]
				]),{class: :select}) %> 
	    <br>  
	    <div class="radio_button"><%= radio_button_tag :media, :video %></div> <span class="radio_btn_opt">Video</span>
	    <div class="radio_button"><%= radio_button_tag :media, :music, checked = true %></div> <span class="radio_btn_opt">Music</span>  
	    <br>
			<%= submit_tag 'Hit It!', class: :hit_button %>
		<% end %>
	</div> 
</div>
</div>

app/views/home/show.html.erb
<body class="render_page">  
	<% if @emotion.name %> 
 
		<% content_for :stylesheets do %>
	  	.render_page {background-color: <%= @colors[rand(0..@colors.size-1)].hexcode %>; }
		<% end %>      
		<% if @selected == 'video' %>		
			<%= render '/partials/video' %>
		<% else @selected == 'music' %>
			<%= render '/partials/images' %>
		<% end %>  

		<%= link_to emotion_media_path(@emotion.name, @alternate), method: :get do%>
			<button class="swap"> 
				<i class="fa fa-play"></i> <span>|</span>
				<i class="fa fa-headphones"></i> 
			</button>	
		<% end %> 

	<% else %>
		<% redirect_to root_path %>
	<% end %> 
</body>  
		
 
<script type="text/javascript">
	function randomColorGen()
  {
    var colors = '<%= @hexcodes %>'; 
		colors = colors.split(',');
    var color = colors[Math.floor(Math.random()* colors.length)]; 
    return color;
	}  
 
 	setInterval(function(){
 		$('.render_page').animate({backgroundColor: randomColorGen() }, 4000)
 	}, 4000);   
</script>

app/views/home/video_form.html.erb
<body class="mediaForm">
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="row clearfix">
				<div class="col-md-6 column" id="boxone">
					<h3 class="topper">
						Enter your own media links here!
					</h3>
				</div>
				<div class="col-md-6 column">
				<h3 class="choose"> Please Choose an Emotion </h3>
					<div class="radio">
  						<label class="radMarg"><input type="radio" name="optradio">Happy</label>
					</div>
					<div class="radio">
  						<label class="radMarg"><input type="radio" name="optradio">Sad</label>
					</div>
					<div class="radio">
  						<label class="radMarg"><input type="radio" name="optradio">Angry</label>
					</div>
					<div class="radio">
  						<label class="radMarg"><input type="radio" name="optradio">Calm</label>
					</div>
				</div>
			</div>
			<div class="row clearfix">
				<div class="col-md-6 column">
					<form role="form">
						<div class="form-group">
						<%= form_tag(home_video_success_path, method: :post) do %>
							 <label for="Video Entry">Give your Video entry a title:</label>
							 <span class="input"> <%= text_field_tag :name %> </span>
						</div>
						<div class="form-group">
							 <label for="Video link">Enter a link for your Video file:</label> <br/>
							 <span class="input"> <%= text_field_tag :file %> </span>
						</div>
						<div class="sub"> <%= submit_tag 'Submit' %> </div>
						<% end %>
					</form>
					<div class="formspace"></div>
				</div>
				<div class="col-md-6 column">
					<form role="form">
						<div class="form-group">
							 <label for="Music Entry">Give your Music entry a title:</label>
							 <span class="input"> <%= text_field_tag :name %> </span>
						</div>
						<div class="form-group">
							 <label for="Music Link">Enter a link for your Music file:</label><br/>
							 <span class="input"> <%= text_field_tag :file %> </span>
						</div>
						<div class="sub"> <%= submit_tag 'Submit' %> </div>
					</form>
					<div class="formspace"></div>
				</div>
			</div>
			<div class="row clearfix">
				<div id="botBoxContainer">
				<div id="bottomBox">
					<form role="form">
						<div class="form-group">
							 <label for="Image Entry">Give your Image entry a title:</label>
							 <span class="inputbottom"> <%= text_field_tag :name %> </span>
						</div>
						<div class="form-group">
							 <label for="Image link">Enter a link for your Image file:</label><br/>
							 <span class="inputbottom"> <%= text_field_tag :file %> </span>
						</div>
						<div class="sub"> <%= submit_tag 'Submit' %> </div>
					</form>
					<div class="formspace"></div>
				</div>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/home/video_success.html.erb
<h1> Video Saved for Review </h1>

<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Animote</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <style><%= yield :stylesheets %></style>
  <link type="text/css" href="/assets/jplayer.blue.monday.css" rel="stylesheet" /> 
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="/assets/jquery.jplayer.min.js"></script>
  <script type="text/javascript" src="/assets/add-on/jplayer.playlist.min.js"></script>
  <script type="text/javascript" src="/assets/bootstrap_js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/assets/jquery.slides.js"></script>

  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  
  <%= csrf_meta_tags %>
  <!-- font -->
  <link href='http://fonts.googleapis.com/css?family=Euphoria+Script' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %> 

</head>
<body>

  <header class="main-nav">
    <%= render '/users/shared/nav' %>
  </header> 
  

  <% if notice %><div id="notice"><%= notice %></div><% end %>
  <% if alert %><div id="alert"><%= alert %></div><% end %>

  <%= yield %>

</body>
</html>

app/views/partials/_images.html.erb
<script>
  $(document).ready(function(){

    var images = '<%= @images_name %>';
    images = images.split(','); 


    $(function(){ 
      $(".slides").slidesjs({
        maxWidth: 1000,
        maxHeight: 625 
      });
    });

    $('.gallery-icon').click(function(){
      $('.default-wrapper').hide();
      $('.gallery-wrapper').show();
      $('.gallery-icon').hide();
      $('.default-container').show();
    });

    $('.default-container').click(function(){
      $('.default-wrapper').show();
      $('.gallery-wrapper').hide();
      $('.default-container').hide();
      $('.gallery-icon').show();
    });

    $('.open-menu').click(function(){
      $('.sidemenu').show();
      $('.open-menu').hide();
      $('.close-menu-container').show();
    });

    $('.close-menu-container').click(function(){
      $('.sidemenu').hide();
      $('.close-menu-container').hide();
      $('.open-menu').show();
    });
  });
</script>


<body>
  <div class="view-icons">
    <a href="#"><i class="fa fa-th fa-2x gallery-icon"></i></a>
    <div class="default-container"><a href="#"><i class="fa fa-square fa-2x default-icon"></i></a></div>
  </div>

  <div class="default-wrapper">
    <% if @emotion.name %>
      <div class="slides default-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
    <% else %> 
      <!-- IMAGE NOT FOUND -->
    <% end %>
  </div>

  <% if @emotion.name %>
    <div class="gallery-wrapper"> 
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
      <div class="slides gallery-view">
        <% find_images(@emotion.name).each do |image| %>
          <img src =<%= image.file %>>
        <% end %>
      </div>
    </div>
  <% else %> 
    <!-- IMAGE NOT FOUND -->
  <% end %>

  <%= render '/partials/menu' %>

  <div class="music-player">
    <%= render '/partials/soundManager2' %>
  </div>

</body>

app/views/partials/_menu.html.erb
<% if current_user %>
  <a href="#"><i class="fa fa-plus fa-2x open-menu"></i></a>
  <div class="close-menu-container"><a href="#"><i class="fa fa-minus fa-2x close-menu"></i></a></div>
  <div class="sidemenu">
    <ul>
      <li><h4><%= current_user.fname + ' ' + current_user.lname %></h4></li><hr>
      <li><h5>Favorites</h5></li><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
      <li><h5><%= link_to 'Upload', home_video_form_path %></h5></li>
      <li><h5><%= link_to 'Settings', edit_user_registration_path(current_user) %></h5></li>
      <li><h5><%= link_to 'Contact Us', home_contact_path %></h5>
    </ul>
  </div>
<% end %>

app/views/partials/_soundManager2.html.erb
<div id="cwrap">
  <div id="nowPlay">
    <div id="npTitle"></div>
  </div>
    <div id="audiowrap">
      <div id="audio0">
        <audio controls autoplay id="audio1" controls="controls" width="300">
          Your browser does not support the HTML5 Audio Tag.
        </audio>
      </div>
      <div id="extraControls">
        <button id="btnNext">Next Track</button>
      </div>
    </div>
  </div>
</div> 

<script type="text/javascript">

  var music_files = '<%= @music_file %>';
  music_files = music_files.split(','); 

  // var music_names = '<%= @music_name %>';
  // music_names = music_names.split(',');
  // console.log(music_names);

  tracks = [];
  for (var i = music_files.length - 1; i >= 0; i--) {
    tracks.push({"track":i, "file":music_files[i]});
  }

    jQuery(function($) {
      var supportsAudio = !!document.createElement('audio').canPlayType;
      if(supportsAudio) {
          var index = Math.floor(Math.random()*music_files.length),
          playing = true;
          mediaPath = src='https://s3.amazonaws.com/emotionsproject/<%= @emotion.name%>+songs/', 
          tracks,
          trackCount = tracks.length,
          npAction = $('#npAction'),
          npTitle = $('#npTitle'),
          audio = $('#audio1').bind('play', function() {
              playing = true;
              npAction.text('Now Playing:');
          }).bind('pause', function() {
              playing = false;
              npAction.text('Paused:');
          }).bind('ended', function() {
              npAction.text('');
              if((index + 1) < trackCount) {
                  index = Math.floor(Math.random()*music_files.length);
                  loadTrack(index);
                  audio.play();
              } else {
                  audio.pause();
                  index = Math.floor(Math.random()*music_files.length);
                  loadTrack(index);
              }
          }).get(0),
          btnPrev = $('#btnPrev').click(function() {
              if((index - 1) > -1) {
                  index--;
                  loadTrack(index);
                  if(playing) {
                      audio.play();
                  }
              } else {
                  audio.pause();
                  index = 0;
                  loadTrack(index);
              }
          }),
          btnNext = $('#btnNext').click(function() {
              if((index + 1) < trackCount) {
                  index = Math.floor(Math.random()*music_files.length);
                  loadTrack(index);
                  if(playing) {
                      audio.play();
                  }
              } else {
                  audio.pause();
                  index = Math.floor(Math.random()*music_files.length);
                  loadTrack(index);
              }
          }),
          li = $('#plUL li').click(function() {
              var id = parseInt($(this).index());
              if(id !== index) {
                  playTrack(id);
              }
          }),
          loadTrack = function(id) {
              $('.plSel').removeClass('plSel');
              $('#plUL li:eq(' + id + ')').addClass('plSel');
              npTitle.text(tracks[id].name);
              index = id;
              audio.src = mediaPath + tracks[id].file;
          },
          playTrack = function(id) {
              loadTrack(id);
              audio.play();
          }; 
          loadTrack(index);
        }
        });
    
</script>

app/views/partials/_video.html.erb
<script>
  $(document).ready(function(){
		$('.open-menu').click(function(){
      $('.sidemenu').show();
      $('.open-menu').hide();
      $('.close-menu-container').show();
    });

    $('.close-menu-container').click(function(){
      $('.sidemenu').hide();
      $('.close-menu-container').hide();
      $('.open-menu').show();
    });
  });

  function nextvid(){
  	location.reload();
  };
</script>

<% if @emotion.name %>
	<% videos = find_videos(@emotion.name) %> 
  <% video = videos[rand(0..videos.size-1)] %> 
  <% name = video.name %>
  <% file = video.file %>  
<% else %> 
	<!-- VIDEO NOT FOUND -->
<% end %>
  
<div id="videoBox">
<iframe width="1100" height="600" src=http://<%= file %>?rel=0&autoplay=1 frameborder="0" allowfullscreen></iframe> <br/>
</div>
<button class="nextBtn" onclick="nextvid()"><i class="fa fa-forward fa-2x"></i></button>

<%= render '/partials/menu' %>

app/views/users/shared/_links.html.erb
<%#- if controller_name != 'sessions' %>
  <%#= link_to "Log in", new_session_path(resource_name) %>
<%# end -%>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: :forgot_password %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_nav.html.erb
<nav class="main-nav">
	<ul>
		<li>  
				<%= link_to image_tag('logo.png'), root_path, class: :logo %> 
		</li>  
		<% if current_user %>
			<!-- signout --> 
			<li class="signin">
				<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: :sign_out_button %> 
			</li>
		<% else %>
			<!-- sign in, sign up --> 
			<li class="signin">
				<span class="dropdown">
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
				    Sign In
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
				    <%= render 'users/sessions/new' %>
				  </ul>
				</span> 
				<span class="dropdown">
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
				    Sign Up
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
				    <%= render '/users/registrations/new' %>
				  </ul>
				</span>
			</li>
		<% end %>
	</ul>
</nav>



<!-- add admin signout -->